image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job will make sure the springboot application compiles and builds.
  stage: build
  script:
    - "cd springboot/twitter-2"
    - "mvn compile"
  artifacts:
    paths:
    - target/ # Artifact for the compiled application

unit-test-job:   # This job runs the unit tests of the application. Should they fail, the CICD will fail
  stage: test
  script:
    - "cd springboot/twitter-2"
    - "mvn test"